version: "3.1"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  elastic:
    image: elasticsearch:7.14.2
    environment:
      - node.name=elasticsearch
      - cluster.name=datasearch
      - cluster.initial_master_nodes=elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
  app:
    ports:
      - 4000:4000
    build: .
    environment:
      DB_URL: ${DB_URL}
      ELASTIC_SEARCH_URL: ${ELASTIC_SEARCH_URL}
    depends_on:
      - mongodb
      - elastic
 
